### ISSUE TITLE
Unable to completely import FO4 NIF with simple animation

### ISSUE THREAD

**Issue by reddraconi** [BadDogSkyrim/PyNifly#304]
I'm attempting to kitbash the `Meshes/SetDressing/CigaretteMachine/CigaretteMachine.nif`
mesh from Fallout 4 in Blender v4.5.3 LTS, but am unable to completely import the `.nif`

PyNifly v20.1 imports the mesh and correctly creates its materials, but fails to import its
animations and reports the following errors in the console:

```
Addon Common: use_bgl_default=False use_gpu_default=True use_gpu_scissor=True
RFCore.register
Override-Wrap function activate_by_id
INFO: Ucupaint 2.3.3 is registered!
INFO:pynifly:Loading pyNifly version 20.1.0
init
INFO: Ucupaint update routine is done in 0.00 ms!
Info: Deleted 3 object(s)
ERROR:pynifly:Cannot import KF: Active object must be an armature.
INFO:pynifly:


====================================
PYNIFLY IMPORT NIF V20.1.0


INFO:pynifly:
        Importing nif: ['E:\\Meshes\\SetDressing\\CigaretteMachine\\CigaretteMachine.nif']
            flags: create_bones | import_anims | import_tris | apply_skinning | import_pose | create_collection | import_collisions
            armature: None
            connect points: [], []
            mesh objects: []

INFO:pynifly:Importing FO4 file E:\Meshes\SetDressing\CigaretteMachine\CigaretteMachine.nif
WARNING:pynifly:Unknown block type: bhkPhysicsSystem
ERROR:pynifly:Import of nif failed
Traceback (most recent call last):
  File "C:\Users\reddr\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\io_scene_nifly\__init__.py", line 1964, in execute
    imp.execute()
  File "C:\Users\reddr\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\io_scene_nifly\__init__.py", line 1744, in execute
    self.import_nif()
  File "C:\Users\reddr\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\io_scene_nifly\__init__.py", line 1659, in import_nif
    self.controller_mgr.import_controller(
  File "C:\Users\reddr\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\io_scene_nifly\controller.py", line 695, in import_controller
    self.anim_name = animation_name if animation_name else ctlr.name
                                                           ^^^^^^^^^
AttributeError: 'NiControllerManager' object has no attribute 'name'
INFO:pynifly:

PyNifly IMPORT of {'CigaretteMachine.nif'} completed WITH ERRORS
====================================


RNA::on_active_object_change -> 'Object003:0'
RNA::on_active_object_change -> 'Object003:0'
Unable to find a suitable DXT compression, falling back to uncompressed (CigaretteMachine_s.dds, 1024x1024).
Unable to find a suitable DXT compression, falling back to uncompressed (CigaretteMachine_n.dds, 1024x1024).
RNA::on_active_object_change -> 'CigaretteMachine01:0'
RNA::on_active_object_change -> 'CigaretteMachine01:0'
```

**Comment by reddraconi** [comment]
This does (kinda) work in v20.0. The same mesh is imported with the animations, but they're incorrect.
The door 's animation is only supposed to move it out a bit, but the key frames makes it look like the door is rotated in global. I think it's supposed to be local? Weird.

<img width="1269" height="999" alt="Image" src="https://github.com/user-attachments/assets/ffc04f57-5b9e-41aa-a9c5-1b23dafe8a49" />

**Comment by BadDogSkyrim** [comment]
I'll have a look. There is apparently a bhkPhysicsSystem block in there and those aren't something I can read, but the rest should work.

**Comment by reddraconi** [comment]
First, sorry for taking so long to get back to you.

I did some side-by-side testing and found the following after immediately importing and exporting the same NIF as previous:

1. The `NiMultiTargetTransformController` has a different number of "Extra Targets".
2. The original Mesh uses `<float_max>` and `<float_min>` where the export has `INF` and `-INF` respectively. (I don't know if that's a problem or not. Probably not.
3. The `NiControllerSequence`s appear in a different order.
4. Some of the `NITransformInterpolator` values didn't copy across. (May be an artifact of 3?)
5. The `NiDefaultAVObjectPalette` has a different number of object links
6. The `bhkNPCollisionObject` is missing on the exported model. Is that what you referenced earlier as not being able to transfer?
7. The animated `NiNode` received a `NiMultiTargetTransformController` where there isn't one on the original mesh.
8. The exported mesh appears to be in the "Close" animation by default. (May be an artifact of 3?)

Screen shots attached for 1-5 and 7. The original is the top and the export is the bottom.

### Comparison Notes 1 and 2
<img width="1281" height="1390" alt="Comparison Notes 1 & 2" src="https://github.com/user-attachments/assets/650c3b3d-ab81-4e73-a53a-21a2ce962dc4" />
### Comparison Note 3
<img width="1281" height="1392" alt="Comparison Note 3" src="https://github.com/user-attachments/assets/f2ce116a-488b-4059-8319-fc153ab929ca" />
### Comparison Note 4
<img width="1279" height="1388" alt="Comparison Note 4" src="https://github.com/user-attachments/assets/dd62c581-dee4-444a-85c0-6b3d8c85ed58" />
### Comparison Note 5
<img width="1278" height="1387" alt="Comparison Note 5" src="https://github.com/user-attachments/assets/9cf6974a-74ca-4273-a891-68886ba888f1" />
### Comparison Note 7
<img width="1281" height="1391" alt="Comparison Note 7" src="https://github.com/user-attachments/assets/5e69d13b-9377-410c-a8d5-cee42c330c9e" />

Please let me know what I can do to assist in the future.

**Comment by BadDogSkyrim** [comment]
Ugh. Okay, I'll work through the issues. Some I'm pretty sure are ok, others need to be addressed.

**Comment by reddraconi** [comment]
Understood, thank you for the detailed write up. I'm sorry for creating extra headaches.

I ran a test with PyNifly v21 and Blender v4.5.4 LTS using the same cigaretteMachine01.nif as posted to this ticket by importing it and immediately re-exporting with these settings:
```
- Rename Bones # Note: probably unnecessary
- Export BODYTRI Extra Data # Note: probably unnecessary
- Export Modifiers
- Export Animations
- Export vertex color/alpha
```

Ran into a few things:
1. The exported animated Object003 mesh portion is getting snapped to (0,0,0) on export.
    > I selected the ROOT empty for export.
2. The object still exports in the 'Close' animation.
    > I ensured the 'Open' animation was selected during export and selected `Object003` as slot in the DopeSheet/Action Editor. I even played the animation and reset it back to frame 1 prior to export. Am I using the new animation feature incorrectly?
