### ISSUE TITLE
Unable to import animations

### ISSUE THREAD

**Issue by eekjacke** [BadDogSkyrim/PyNifly#310]
Using latest release (20.1). Animations fail to be imported, worked using a previous version (19.6). Please let me know if I can provide any more info, cheers. :)
```
`ERROR:pynifly:Error importing controllers Door
Traceback (most recent call last):
  File "C:\Users\eekja\AppData\Roaming\Blender Foundation\Blender\4.4\scripts\addons\io_scene_nifly\__init__.py", line 906, in import_ninode
    self.controller_mgr.import_controller(ninode.controller, arma if arma else obj, obj)
  File "C:\Users\eekja\AppData\Roaming\Blender Foundation\Blender\4.4\scripts\addons\io_scene_nifly\controller.py", line 695, in import_controller
    self.anim_name = animation_name if animation_name else ctlr.name
                                                           ^^^^^^^^^
AttributeError: 'NiMultiTargetTransformController' object has no attribute 'name'
ERROR:pynifly:Import of nif failed
Traceback (most recent call last):
  File "C:\Users\eekja\AppData\Roaming\Blender Foundation\Blender\4.4\scripts\addons\io_scene_nifly\__init__.py", line 1964, in execute
    imp.execute()
  File "C:\Users\eekja\AppData\Roaming\Blender Foundation\Blender\4.4\scripts\addons\io_scene_nifly\__init__.py", line 1744, in execute
    self.import_nif()
  File "C:\Users\eekja\AppData\Roaming\Blender Foundation\Blender\4.4\scripts\addons\io_scene_nifly\__init__.py", line 1659, in import_nif
    self.controller_mgr.import_controller(
  File "C:\Users\eekja\AppData\Roaming\Blender Foundation\Blender\4.4\scripts\addons\io_scene_nifly\controller.py", line 695, in import_controller
    self.anim_name = animation_name if animation_name else ctlr.name
                                                           ^^^^^^^^^
AttributeError: 'NiControllerManager' object has no attribute 'name'
INFO:pynifly:

PyNifly IMPORT of {'carth1024v2.nif'} completed WITH ERRORS
====================================
```
